#!/bin/sh
#
# Starts wifi networking on rpi zero 2w
#
start() {
  printf 'Starting bluetooth'
  
  modprobe btbcm
  modprobe hci_uart

  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi

  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
  return "$status"
}

stop() {
  printf 'Stopping bluetooth'
  rmmod btbcm
  rmmod hci_uart
  status=$?
  if [ "$status" -eq 0 ]; then
    echo "OK"
  else
    echo "FAIL"
  fi
  return "$status"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start|stop|restart)
    "$1";;
  reload)
    # Restart, since there is no true "reload" feature.
    restart;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
